version: "3.8"
services:
  pharmacy-recommendation-redis: # 서비스명
    container_name: pharmacy-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: wofud/pharmacy-recommendation-redis
    ports:
      - "6379:6379"
    networks:
      - pharmacy_network
  pharmacy-recommendation-database: # 서비스명
    container_name: pharmacy-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: wofud/pharmacy-recommendation-database
    environment:
      - MARIADB_DATABASE=pharmacy-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD} # 패스워드는 외부에 공개되면 안되므로 env파일에 설정, 별다른 설정없이 env파일이 있으면 알아서 가져온다.
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - pharmacy_network